# Generated by Django 4.2.7 on 2023-11-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ganadores",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("cedula", models.CharField(max_length=10)),
                ("nombre", models.CharField(max_length=255)),
                ("provincia", models.CharField(max_length=255, null=True)),
                ("escuela", models.CharField(max_length=255, null=True)),
                ("genero", models.CharField(max_length=1)),
                ("categoria", models.CharField(max_length=3)),
                ("prueba", models.CharField(max_length=3)),
                ("distancia", models.CharField(max_length=3)),
                ("tiempo_registro", models.FloatField(blank=True, null=True)),
                ("tiempo_competencia", models.FloatField(blank=True, null=True)),
                ("puesto", models.IntegerField(blank=True, null=True)),
                ("puntaje", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
