# Generated by Django 4.2.7 on 2023-11-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cedula", models.CharField(max_length=10)),
                ("nombre", models.CharField(max_length=255)),
                ("provincia", models.CharField(max_length=255, null=True)),
                ("escuela", models.CharField(max_length=255, null=True)),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")], max_length=1
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("MEN", "Menores 6 años"),
                            ("7-8", "7-8 años"),
                            ("9NO", "9 años novatos"),
                            ("9CL", "9 años clasificados"),
                            ("10N", "10 años novatos"),
                            ("10C", "10 años clasificados"),
                            ("11N", "11 años novatos"),
                            ("11C", "11 años clasificados"),
                            ("12N", "12 años novatos"),
                            ("12C", "12 años clasificados"),
                            ("34N", "13-14 años novatos"),
                            ("34C", "13-14 años clasificados"),
                            ("57N", "15-17 años novatos"),
                            ("57C", "15-17 años clasificados"),
                            ("18N", "18 en adelante novatos"),
                            ("18C", "18 en adelante clasificados"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "manana1_prueba",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MAR", "Mariposa"),
                            ("ESP", "Espalda"),
                            ("COM", "Combinado"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "manana1_distancia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("25M", "25 metros"),
                            ("50M", "50 metros"),
                            ("10M", "100 metros"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("manana1_tiempo", models.FloatField(blank=True, null=True)),
                (
                    "manana2_prueba",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MAR", "Mariposa"),
                            ("ESP", "Espalda"),
                            ("COM", "Combinado"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "manana2_distancia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("25M", "25 metros"),
                            ("50M", "50 metros"),
                            ("10M", "100 metros"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("manana2_tiempo", models.FloatField(blank=True, null=True)),
                (
                    "tarde1_prueba",
                    models.CharField(
                        blank=True,
                        choices=[("LIB", "Libre"), ("PEC", "Pecho")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "tarde1_distancia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("25M", "25 metros"),
                            ("50M", "50 metros"),
                            ("10M", "100 metros"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("tarde1_tiempo", models.FloatField(blank=True, null=True)),
                (
                    "tarde2_prueba",
                    models.CharField(
                        blank=True,
                        choices=[("LIB", "Libre"), ("PEC", "Pecho")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "tarde2_distancia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("25M", "25 metros"),
                            ("50M", "50 metros"),
                            ("10M", "100 metros"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("tarde2_tiempo", models.FloatField(blank=True, null=True)),
                (
                    "opcional1_prueba",
                    models.CharField(
                        blank=True,
                        choices=[("REL", "Relevos"), ("SNO", "Snorkel")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "opcional1_distancia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("25M", "25 metros"),
                            ("50M", "50 metros"),
                            ("10M", "100 metros"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("opcional1_tiempo", models.FloatField(blank=True, null=True)),
                (
                    "opcional2_prueba",
                    models.CharField(
                        blank=True,
                        choices=[("REL", "Relevos"), ("SNO", "Snorkel")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "opcional2_distancia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("25M", "25 metros"),
                            ("50M", "50 metros"),
                            ("10M", "100 metros"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("opcional2_tiempo", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
